"use client";
import Sidebar from "@/components/Sidebar";
import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { ContextProvider } from "../context/Context";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`bg-[#F1F5F9] flex p-[25px] ${poppins.variable}`}>
        <ContextProvider>
          {/* <Sidebar /> */}
          {children}
        </ContextProvider>
      </body>
    </html>
  );
}
